# Generated by Django 2.2.4 on 2019-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190913_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('General Question', 'General Question'), ('Identity Request', 'Identity Request'), ('Troubleshoot Request', 'Troubleshoot Request')], default='General Question', max_length=50),
        ),
    ]
