# Generated by Django 2.2.4 on 2019-08-23 05:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('botanical_name', models.CharField(max_length=100)),
                ('alternative_names', models.CharField(max_length=255)),
                ('sun_requirements', models.TextField()),
                ('soil_requirements', models.TextField()),
                ('watering_frequency', models.TextField()),
                ('fertilizer_frequency', models.TextField()),
                ('toxicity', models.TextField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_pics', verbose_name='Image')),
                ('plant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plant.Plant')),
            ],
        ),
    ]
