# Generated by Django 2.2.4 on 2019-09-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20190828_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='alternative_names',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='fertilizer_frequency',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sun_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='toxicity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency',
            field=models.TextField(blank=True),
        ),
    ]
