# Generated by Django 2.2.4 on 2019-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20190913_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='alternative_names',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
